export const GET_ALL_DOGS = 'GET_ALL_DOGS';
export const GET_DOG_DETAIL = 'GET_DOG_DETAIL';
export const POST_DOG = 'POST_DOG';
export const CLEAR_INFO_POST = 'CLEAR_INFO_POST';
export const GET_ALL_TEMPERAMENTS = 'GET_ALL_TEMPERAMENTS';